config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Application error routes
  get '/404', to: 'error#not_found', via: :all
  get '/422', to: 'error#unprocessable_entity', via: :all
  get '/500', to: 'error#internal_server_error', via: :all

  # Dashboard routes
  constraints subdomain: 'dashboard' do
    devise_for :users, controllers: { sessions: 'users/sessions' }
    namespace :dashboard, path: '' do
      root to: 'dashboard#index', as: ''
      resources :topics
      resources :videos, only: %i[index new create]
      resources :playlists do
        get :videos, on: :member
        resources :videos, except: %i[index new create] do
          resources :links
          resource :transcription, only: %i[show create update destroy]
          resource :show_note, only: %i[show create update destroy]
          put :move, on: :member
        end
      end
      resources :users
      resources :opinions
      resource :searches, only: %i[show]

      # Pending actions
      namespace :pending do
        resource :tags, only: %w[show update]
        resource :transcriptions, only: :show
        resource :show_notes, only: :show
      end
    end
  end

  # Main application routes
  root to: 'front#index'

  # Early access.
  get '/early' => redirect('http://early.makigas.es', status: 302)
  get '/early/videos', to: 'videos#early', format: :json

  # Legacy RSS feeds, must come first or there will be conflicts.
  get '/videos/feed' => redirect('/videos.atom')
  get '/temas/:topic/feed' => redirect('/temas/%{topic}.atom')
  get '/series/:playlist/feed' => redirect('/series/%{playlist}.atom')

  resources :topics, path: 'temas', only: %i[index show] do
    get :feed, on: :member, format: :xml
  end

  resources :videos, only: :index

  resources :playlists, path: 'series', only: %i[index show] do
    resources :videos, path: '/', only: :show
  end
  get :terms, path: 'terminos', to: 'pages#terms'
  get :privacy, path: 'privacidad', to: 'pages#privacy'
  get :disclaimer, path: 'responsabilidades', to: 'pages#disclaimer'
  get :cookies, to: 'pages#cookies'
  get :discord, to: 'pages#discord'

  get :dnt, to: 'pages#dnt'

  get '/v/:id', to: 'videos#find_by_id'

  # Legacy routes (redirect only).
  get '/videos/:topic/:playlist/episodio/:video' => redirect('/series/%{playlist}/%{video}')
  get '/videos/:topic/:playlist' => redirect('/series/%{playlist}')
  get '/videos/:playlist' => redirect('/series/%{playlist}')

  # Legacy routes for the old topic explorer
  get '/topics/:topic' => redirect('/temas/%{topic}')
  get '/topics/:topic/feed' => redirect('/temas/%{topic}.atom')
  get '/topics' => redirect('/temas')

  # Legacy routes for the text pages.
  get '/terms' => redirect('/terminos')
  get '/privacy' => redirect('/privacidad')
  get '/disclaimer' => redirect('/responsabilidades')
  get '/about/dnt' => redirect('/dnt')

  if Rails.env.development?
    mount Lookbook::Engine, at: '/lookbook'
    match('/delayed_job' => DelayedJobWeb, :anchor => false, :via => %i[get post])
  end
end

app/models/topic.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: topics
#
#  id                     :integer          not null, primary key
#  color                  :string
#  description            :string           not null
#  forum_url              :string
#  slug                   :string           not null
#  thumbnail_content_type :string
#  thumbnail_file_name    :string
#  thumbnail_file_size    :bigint
#  thumbnail_updated_at   :datetime
#  title                  :string           not null
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  parent_topic_id        :bigint
#
# Indexes
#
#  index_topics_on_parent_topic_id  (parent_topic_id)
#  index_topics_on_slug             (slug) UNIQUE
#
class Topic < ApplicationRecord
  extend FriendlyId

  friendly_id :title, use: :slugged

  belongs_to :parent_topic, class_name: 'Topic', optional: true
  has_many :child_topics, class_name: 'Topic', inverse_of: :parent_topic, foreign_key: :parent_topic_id,
                          dependent: :nullify

  has_attached_file :thumbnail, styles: {
    thumbnail: '100x100>',
    small: '180x180>',
    default: '360x360>',
    hidef: '720x720>'
  }, default_url: '/makigas.png'

  validates :title, presence: true, length: { maximum: 50 }
  validates :description, presence: true, length: { maximum: 250 }
  validates :color, presence: true
  validates :thumbnail, presence: true
  validates_attachment :thumbnail, content_type: { content_type: %r{\Aimage/.*\z} }

  # Playlists can survive without a topic, so on delete set the topic to null.
  has_many :playlists, dependent: :nullify

  def playlists_with_children
    my_playlists = Playlist.where(topic_id: id)
    child_topics = Topic.where(parent_topic_id: id)
    child_playlists = Playlist.where(topic_id: child_topics)
    my_playlists.or(child_playlists)
  end

  def content_updated_at
    [updated_at, playlists.pluck(:updated_at).max].compact.flatten.max
  end

  def ancestors
    return [] if parent_topic_id.blank?

    parent_topic.ancestors.tap { |arr| arr << parent_topic }
  end

  def to_s
    title
  end

  # Returns a HATEOAS-friendly representation of the thumbnails.
  def icons
    %i[hidef default thumbnail].map do |style|
      { href: thumbnail.url(style),
        type: thumbnail.content_type,
        sizes: thumbnail.styles[style].geometry.gsub('>', '') }
    end
  end
end

app/controllers/dashboard/topics_controller.rb
# frozen_string_literal: true

module Dashboard
  class TopicsController < Dashboard::DashboardController
    before_action :topic_set, only: %i[show edit update destroy]

    def index
      @topics = Topic.order(updated_at: :desc).page(params[:page])
    end

    def show; end

    def new
      @topic = Topic.new
    end

    def edit; end

    def create
      @topic = Topic.new(topic_params)
      if @topic.save
        redirect_to [:dashboard, @topic], notice: t('.created')
      else
        render :new
      end
    end

    def update
      if @topic.update(topic_params)
        redirect_to [:dashboard, @topic], notice: t('.updated')
      else
        render :edit
      end
    end

    def destroy
      @topic.destroy!
      redirect_to %i[dashboard topics], notice: t('.destroyed')
    end

    private

    def topic_params
      params.require(:topic).permit(:title, :description, :color, :thumbnail, :forum_url, :parent_topic_id)
    end

    def topic_set
      @topic = Topic.friendly.find(params[:id])
    end
  end
end

app/controllers/topics_controller.rb
# frozen_string_literal: true

class TopicsController < ApplicationController
  before_action :topic_set, only: %i[show]

  def index
    @topics = Topic.all
  end

  def show
    respond_to do |format|
      format.any(:html, :json)
      format.atom do
        @videos = Video.visible.includes(playlist: :topic)
                       .where(playlists: { topic_id: @topic.id }).order(published_at: :desc).limit(15)
      end
    end
  end

  private

  def topic_set
    @topic = Topic.friendly.find(params[:id])
    redirect_to topic_path(@topic) if params[:id] != @topic.slug
  end
end

app/views/topics/contents.html.erb
<h1><%= link_to @topic.title, topic_path(@topic) %></h1>
<h2><%= t('.title') %></h2>

<table class="table table-default">
  <thead>
    <tr>
      <th><%= t('.position') %></th>
      <th><%= t('.playlist') %></th>
      <th colspan="3"><%= t('.operations') %></th>
    </tr>
  </thead>
  <tbody>
    <% @topic.playlists.each do |playlist| %>
    <tr>
      <td><%= playlist.position %></td>
      <td class="col-expand"><%= playlist.title %></td>
      <td class="col-mini">
        <%= button_to sort_topic_path(@topic), method: :put, class: 'btn btn-default btn-xs' do %>
          <%= hidden_field_tag :playlist, playlist.id %>
          <%= hidden_field_tag :operation, :up %>
          <%= t('.up') %>
        <% end unless playlist.first? %>
      </td>
      <td class="col-mini">
        <%= button_to sort_topic_path(@topic), method: :put, class: 'btn btn-default btn-xs' do %>
          <%= hidden_field_tag :playlist, playlist.id %>
          <%= hidden_field_tag :operation, :down %>
          <%= t('.down') %>
        <% end unless playlist.last? %>
      </td>
      <td class="col-mini">
        <%= button_to sort_topic_path(@topic), method: :put, class: 'btn btn-danger btn-xs' do %>
          <%= hidden_field_tag :playlist, playlist.id %>
          <%= hidden_field_tag :operation, :unlink %>
          <%= t('.unlink') %>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/topics/feed.xml.erb
<?xml version="1.0" encoding="utf-8" ?>
<feed xmlns="http://www.w3.org/2005/Atom" xml:lang="es-ES">
  <title type="text">makigas (<%= @topic.title %>)</title>
  <subtitle type="text">Vídeos recientes publicados en el tema <%= @topic.title %></subtitle>
  <updated><%= @updated_at.iso8601 %></updated>
  <id><%= feed_topic_url(@topic) %></id>
  <icon><%= @topic.thumbnail.url %></icon>
  <logo><%= @topic.thumbnail.url %></logo>
  <link rel="self" href="<%= feed_topic_url(@topic) %>" type="application/atom+xml" />
  <link rel="alternate" href="<%= topic_url(@topic) %>" type="text/html" />
  <author><name>makigas.es</name></author>
  <generator uri="https://github.com/makigas/makigas">makigas.es</generator>
  <%- @videos.each do |video| -%>
    <%= render 'videos/atom', video: video %>
  <%- end -%>
</feed>

app/views/topics/index.html.erb
<% content_for :title, "#{t('.meta.title')} – makigas" %>
<% content_for :description, t('.meta.description') %>
<% content_for :hero do %>
  <h1><%= t('.title') %></h1>
<% end %>
<%= render Six::Base::WrapperComponent.new(classes: 'topicslist', breath: true) do %>
  <% @topics.each do |tp| %>
    <%= render Six::Explorer::TopicCardComponent.new(topic: tp) %>
  <% end %>
<% end %>

app/views/topics/show.atom.erb
<?xml version="1.0" encoding="utf-8" ?>
<feed xmlns="http://www.w3.org/2005/Atom" xml:lang="es-ES">
  <title type="text">makigas (<%= @topic.title %>)</title>
  <subtitle type="text">Vídeos recientes publicados en el tema <%= @topic.title %></subtitle>
  <updated><%= @videos.pluck(:updated_at).max.iso8601 %></updated>
  <id><%= topic_url(@topic, format: :atom) %></id>
  <icon><%= @topic.thumbnail.url %></icon>
  <logo><%= @topic.thumbnail.url %></logo>
  <link rel="self" href="<%= topic_url(@topic, format: :atom) %>" type="application/atom+xml" />
  <link rel="alternate" href="<%= topic_url(@topic) %>" type="text/html" />
  <author><name>makigas.es</name></author>
  <generator uri="https://github.com/makigas/makigas">makigas.es</generator>
  <%= render partial: 'videos/video', collection: @videos %>
</feed>

app/views/topics/show.html.erb
<% content_for :title, "#{@topic.title} – makigas" %>
<% content_for :description, "#{@topic.description} #{t('.meta.description')}" %>
<% content_for :twitter do %>
  <meta name="twitter:card" content="summary">
  <meta name="twitter:site" content="@makigas">
  <meta name="twitter:title" content="<%= @topic.title %>">
  <meta name="twitter:description" content="<%= @topic.description %>">
  <meta name="twitter:image" content="<%= image_url(@topic.thumbnail.url, only_path: false) %>">
<% end %>
<% content_for :facebook do %>
  <meta property="og:url" content="<%= canonical_url %>">
  <meta property="og:title" content="<%= @topic.title %>">
  <meta property="og:type" content="website">
  <meta property="og:description" content="<%= @topic.description %>">
  <meta property="og:site_name" content="makigas">
  <meta property="og:image" content="<%= image_url(@topic.thumbnail.url, only_path: false) %>">
<% end %>
<% content_for :meta do %>
  <%= tag(:link, rel: :alternate, href: topic_url(@topic, format: :atom), title: t('.meta.topic_feed', topic: @topic.title), type: 'application/atom+xml') %>
<% end %>
<% content_for :header do %>
  <style>
    :root {
      --navbar-background: <%= @topic.color.paint.darken(20) %>;
      --jumbo-background: <%= @topic.color.paint.darken(20) %>;
      --playlist-card-hover-background: <%= @topic.color.paint.desaturate(35).lighten(35) %>;
    }
  </style>
<% end %>
<% content_for(:hero) do %>
  <h1><%= @topic.title %></h1>
<% end %>
<%= render Six::Explorer::PlaylistListComponent.new(playlists: @topic.playlists_with_children.with_public_videos) %>