config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Application error routes
  get '/404', to: 'error#not_found', via: :all
  get '/422', to: 'error#unprocessable_entity', via: :all
  get '/500', to: 'error#internal_server_error', via: :all

  # Dashboard routes
  constraints subdomain: 'dashboard' do
    devise_for :users, controllers: { sessions: 'users/sessions' }
    namespace :dashboard, path: '' do
      root to: 'dashboard#index', as: ''
      resources :topics
      resources :videos, only: %i[index new create]
      resources :playlists do
        get :videos, on: :member
        resources :videos, except: %i[index new create] do
          resources :links
          resource :transcription, only: %i[show create update destroy]
          resource :show_note, only: %i[show create update destroy]
          put :move, on: :member
        end
      end
      resources :users
      resources :opinions
      resource :searches, only: %i[show]

      # Pending actions
      namespace :pending do
        resource :tags, only: %w[show update]
        resource :transcriptions, only: :show
        resource :show_notes, only: :show
      end
    end
  end

  # Main application routes
  root to: 'front#index'

  # Early access.
  get '/early' => redirect('http://early.makigas.es', status: 302)
  get '/early/videos', to: 'videos#early', format: :json

  # Legacy RSS feeds, must come first or there will be conflicts.
  get '/videos/feed' => redirect('/videos.atom')
  get '/temas/:topic/feed' => redirect('/temas/%{topic}.atom')
  get '/series/:playlist/feed' => redirect('/series/%{playlist}.atom')

  resources :topics, path: 'temas', only: %i[index show] do
    get :feed, on: :member, format: :xml
  end

  resources :videos, only: :index

  resources :playlists, path: 'series', only: %i[index show] do
    resources :videos, path: '/', only: :show
  end
  get :terms, path: 'terminos', to: 'pages#terms'
  get :privacy, path: 'privacidad', to: 'pages#privacy'
  get :disclaimer, path: 'responsabilidades', to: 'pages#disclaimer'
  get :cookies, to: 'pages#cookies'
  get :discord, to: 'pages#discord'

  get :dnt, to: 'pages#dnt'

  get '/v/:id', to: 'videos#find_by_id'

  # Legacy routes (redirect only).
  get '/videos/:topic/:playlist/episodio/:video' => redirect('/series/%{playlist}/%{video}')
  get '/videos/:topic/:playlist' => redirect('/series/%{playlist}')
  get '/videos/:playlist' => redirect('/series/%{playlist}')

  # Legacy routes for the old topic explorer
  get '/topics/:topic' => redirect('/temas/%{topic}')
  get '/topics/:topic/feed' => redirect('/temas/%{topic}.atom')
  get '/topics' => redirect('/temas')

  # Legacy routes for the text pages.
  get '/terms' => redirect('/terminos')
  get '/privacy' => redirect('/privacidad')
  get '/disclaimer' => redirect('/responsabilidades')
  get '/about/dnt' => redirect('/dnt')

  if Rails.env.development?
    mount Lookbook::Engine, at: '/lookbook'
    match('/delayed_job' => DelayedJobWeb, :anchor => false, :via => %i[get post])
  end
end

app/models/video.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: videos
#
#  id               :integer          not null, primary key
#  description      :text             not null
#  duration         :integer          not null
#  early_access     :boolean          default(FALSE), not null
#  old_playlist_ids :integer          default([]), not null, is an Array
#  position         :integer          not null
#  published_at     :datetime         not null
#  slug             :string           not null
#  tags             :string           default([]), is an Array
#  title            :string           not null
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  playlist_id      :integer          not null
#  twitch_id        :string
#  youtube_id       :string           not null
#
# Indexes
#
#  index_videos_on_early_access      (early_access)
#  index_videos_on_old_playlist_ids  (old_playlist_ids)
#  index_videos_on_slug              (slug)
#  index_videos_on_youtube_id        (youtube_id) UNIQUE
#
class Video < ApplicationRecord
  extend FriendlyId

  include MeiliSearch::Rails
  meilisearch enqueue: true, raise_on_failure: Rails.env.development? do
    attribute :title, :description

    attribute(:transcription) { transcription&.content }
    attribute(:show_note) { show_note&.content }

    attribute :slug
    attribute :tags

    attribute(:playlist_title) { playlist.title }
    attribute(:playlist_description) { playlist.description }
    attribute(:playlist_slug) { playlist.slug }

    attribute(:topic_title) { playlist.topic&.title }
    attribute(:topic_description) { playlist.topic&.description }
    attribute(:topic_slug) { playlist.topic&.slug }

    attribute :duration
    filterable_attributes %i[topic_slug duration tags]
  end

  # Videos are sorted in a playlist.
  belongs_to :playlist
  has_many :links, dependent: :destroy
  acts_as_list scope: :playlist

  # Slug. Can be repeated as long as it's on different playlists.
  friendly_id :title, use: %i[slugged scoped history], scope: :playlist

  # Old playlist ID
  before_update :track_old_playlist_id, if: :will_save_change_to_playlist_id?
  scope :filter_by_old_playlist_id, ->(id) { id ? where('old_playlist_ids @> ARRAY[?]::integer[]', id) : self }

  # Scope for limiting the amount of videos to those actually published.
  scope :visible, -> { where('published_at <= ?', DateTime.now) }

  # Scope for getting videos that are available for early access.
  scope :early_access, lambda {
    where(early_access: true).where('published_at > ?', DateTime.now).where.not(twitch_id: nil)
  }

  # Filterable scopes
  scope :filter_by_length, ->(duration) { where(LENGTH_QUERIES[duration]) }
  scope :filter_by_topic, ->(slug) { includes(playlist: :topic).where('topic.slug' => slug) }
  scope :filter_by_tag, ->(tag) { tag ? where('tags @> ARRAY[?]::varchar[]', tag) : self }

  # Tags
  scope :untagged, -> { where("tags = '{}'") }
  scope :untranscribed, -> { where.missing(:transcription).distinct }
  scope :unnoted, -> { where.missing(:show_note).distinct }

  # Validations.
  validates :title, presence: true, length: { maximum: 100 }
  validates :description, presence: true, length: { maximum: 1500 }
  validates :youtube_id, presence: true, length: { maximum: 15 }
  validates :duration, presence: true, numericality: { greater_than: 0 }
  validates :published_at, presence: true

  has_one :show_note, dependent: :destroy, as: :documentable
  has_one :transcription, dependent: :destroy, as: :documentable

  def self.free_filter(filter_params)
    filter_params.to_h.reduce(Video.visible) do |videos, (key, value)|
      scope = "filter_by_#{key}"
      return videos unless videos.respond_to?(scope)

      videos.send(scope, value)
    end
  end

  def self.tags
    pluck(Arel.sql('DISTINCT unnest(tags)'))
  end

  # Natural duration
  def natural_duration=(dur)
    self.duration = ApplicationController.helpers.extract_time dur
  end

  def natural_duration
    return nil if duration.blank?

    hours = duration / 3600
    minutes = (duration % 3600) / 60
    seconds = duration % 60
    [hours.to_s.rjust(2, '0'), minutes.to_s.rjust(2, '0'), seconds.to_s.rjust(2, '0')].join(':')
  end

  # Visible videos are those whose publication date has been already reached.
  # Therefore this videos are visible on lists, playlists, searches...
  def visible?
    published_at <= DateTime.now
  end

  # Scheduled videos are those whose publication date has not been reached yet.
  # Showing content for this video would spoil the experience and therefore
  # they should be excluded from searches, lists, playlists...
  def scheduled?
    published_at > DateTime.now
  end

  def track_old_playlist_id
    old_playlist_ids << playlist_id_was
  end

  delegate :to_s, to: :title

  LENGTH_QUERIES = {
    'short' => 'duration <= 300',
    'medium' => 'duration > 300 and duration <= 900',
    'long' => 'duration > 900'
  }.freeze

  # rubocop:disable Metrics/AbcSize, Metrics/MethodLength
  def to_episode_schema
    { name: title,
      description:,
      keywords: tags,
      dateCreated: created_at.iso8601,
      dateModified: updated_at.iso8601,
      datePublished: published_at&.iso8601,
      timeRequired: schema_duration,
      duration: schema_duration,
      image: playlist.card.url(:default),
      thumbnailUrl: playlist.thumbnail.url(:thumb),
      episodeNumber: position }
  end
  # rubocop:enable Metrics/AbcSize, Metrics/MethodLength

  def to_video_schema
    { name: title,
      description:,
      thumbnailUrl: "https://i1.ytimg.com/vi/#{youtube_id}/mqdefault.jpg",
      uploadDate: published_at ? published_at&.iso8601 : created_at.iso8601,
      duration: schema_duration,
      embedUrl: "https://www.youtube.com/embed/#{youtube_id}" }
  end

  def schema_duration
    ActiveSupport::Duration.build(duration).iso8601
  end
end

app/controllers/dashboard/videos_controller.rb
# frozen_string_literal: true

module Dashboard
  class VideosController < Dashboard::DashboardController
    before_action :video_set, only: %i[show edit update destroy move]

    DEFAULT_SORT_CRITERIA = 'released'

    def index
      @sorter = VideoSorter.new(query: params[:sort] || DEFAULT_SORT_CRITERIA)
      @videos = @sorter.videos.page(params[:page])
    end

    def show; end

    def new
      @video = Video.new.tap do |video|
        video.playlist_id = params[:playlist_id] if params[:playlist_id].present?
      end
    end

    def edit; end

    def create
      @video = Video.new(video_params)
      if @video.save
        redirect_to (params[:return_to] || [:dashboard, @video.playlist, @video]), notice: t('.created')
      else
        render :new
      end
    end

    def update
      if @video.update(video_params)
        redirect_to [:dashboard, @video.playlist, @video], notice: t('.updated')
      else
        render :edit
      end
    end

    def destroy
      @video.destroy!
      redirect_to %i[dashboard videos], notice: t('.destroyed')
    end

    def move
      move!(@video, params[:direction])
      respond_to do |format|
        format.json { render json: { position: @video.position, direction: params[:direction] } }
        format.html { redirect_to [:videos, :dashboard, @video.playlist], notice: t('.moved') }
      end
    end

    private

    def move!(video, direction)
      case direction
      when 'up'
        video.move_higher
      when 'down'
        video.move_lower
      else
        raise 'Unsupported direction'
      end
    end

    def video_set
      @playlist = Playlist.friendly.find(params[:playlist_id])
      @video = @playlist.videos.friendly.find(params[:id])
    end

    def video_params
      params.require(:video).permit(:title, :description, :youtube_id, :duration, :twitch_id, :early_access,
                                    :tags, :playlist_id, :published_at).tap do |video_params|
        video_params[:tags] = video_params[:tags].split if video_params[:tags].present?
      end
    end
  end
end

app/controllers/videos_controller.rb
# frozen_string_literal: true

class VideosController < ApplicationController
  rescue_from Makigas::SearchError, with: :search_error

  def search_error
    render :search_error, status: :service_unavailable
  end

  def index
    @videos = if filter_params.present?
                VideoSearch.new(params[:q], filters: filter_params, page:).videos
              else
                Video.visible.includes(playlist: :topic).order(published_at: :desc).page(page).per(10)
              end
  end

  def show
    find_video
    raise ActiveRecord::RecordNotFound unless @video.present? && @video.visible?

    redirect_to [@video.playlist, @video], status: :moved_permanently unless canonical_params?
  end

  def find_by_id
    @video = Video.find_by!(youtube_id: params[:id])
    redirect_to playlist_video_path(@video, playlist_id: @video.playlist)
  end

  def early
    @videos = Video.early_access
    respond_to do |format|
      format.json
    end
  end

  private

  def find_video
    @playlist = Playlist.friendly.find(params[:playlist_id])
    @video = @playlist.videos.friendly.find(params[:id], allow_nil: true)
    find_video_in_old_playlist if @video.blank?
  end

  # Second chance: the video was not found in this playlist, let's see if the URL points
  # an old permalink by checking videos that *used* to be in this playlist and test if
  # any of these videos has or used to have the video slug provided in the permalink.
  def find_video_in_old_playlist
    old_videos = Video.filter_by_old_playlist_id(@playlist.id)
    @video = old_videos.friendly.find(params[:id], allow_nil: true)
    @playlist = @video.playlist if @video.present?
  end

  def page
    params.fetch(:page, 1)
  end

  def filter_params
    params.permit(:q, :length, :tag, topic: [])
  end

  def canonical_params?
    params[:playlist_id] == @playlist.slug && params[:id] == @video.slug
  end
end

app/helpers/dashboard/videos_helper.rb
# frozen_string_literal: true

module Dashboard
  module VideosHelper
    def dashboard_derive_video_list_params(filters = {})
      valid_filters = filters.slice(:sort, :page)
      url_for(request.query_parameters.merge(valid_filters))
    end

    def dashboard_video_path(video, options = {})
      dashboard_playlist_video_path(video, options.merge(playlist_id: video.playlist))
    end

    def edit_dashboard_video_path(video, options = {})
      edit_dashboard_playlist_video_path(video, options.merge(playlist_id: video.playlist))
    end

    def move_dashboard_video_path(video, options = {})
      move_dashboard_playlist_video_path(video, options.merge(playlist_id: video.playlist))
    end

    def dashboard_video_url(video, options = {})
      dashboard_playlist_video_url(video, options.merge(playlist_id: video.playlist))
    end

    def edit_dashboard_video_url(video, options = {})
      edit_dashboard_playlist_video_url(video, options.merge(playlist_id: video.playlist))
    end

    def move_dashboard_video_url(video, options = {})
      move_dashboard_playlist_video_url(video, options.merge(playlist_id: video.playlist))
    end
  end
end

app/helpers/videos_helper.rb
# frozen_string_literal: true

module VideosHelper
  def forum_utm_params(video)
    { campaign: 'NuevoForo2024', source: 'makigas.es', medium: 'SubBanner',
      terrm: video.playlist_id, content: video.id }
  end

  # rubocop:disable Metrics/MethodLength
  def video_episode_jsonld(video)
    video.to_episode_schema.merge(partOfSeries: playlist_jsonld(video.playlist)).deep_merge(
      '@context': 'https://schema.org/',
      '@type': 'Episode',
      publisher: {
        '@type': 'Organization',
        name: 'makigas',
        url: 'https://www.makigas.es'
      },
      author: {
        '@type': 'Person',
        name: 'Dani Rodríguez'
      }
    )
  end
  # rubocop:enable Metrics/MethodLength

  def video_object_jsonld(video)
    video.to_video_schema.merge(encodesCreativeWork: video_episode_jsonld(video)).deep_merge(
      '@context': 'https://schema.org/',
      '@type': 'VideoObject',
      sameAs: "https://www.youtube.com/watch?v=#{video.youtube_id}",
      url: playlist_video_path(video, playlist_id: video.playlist_id)
    )
  end

  def video_path(video, options = {})
    playlist_video_path(video, options.merge(playlist_id: video.playlist))
  end

  def video_url(video, options = {})
    playlist_video_url(video, options.merge(playlist_id: video.playlist))
  end

  def derive_search_url(filters = {})
    valid_filters = filters.slice(:tag, :topic, :length, :q)
    url_for(request.query_parameters.merge(valid_filters))
  end

  def video_search_duration_filters
    [['Cortos (<5 min)', 'short'],
     ['Medios (5 a 15 min)', 'medium'],
     ['Largos (>15 min)', 'long']]
  end
end

app/views/videos/_atom.xml.erb
<entry>
  <id><%= video_url(video) %></id>
  <updated><%= video.published_at.iso8601 %></updated>
  <link rel="alternate" href="<%= video_url(video) %>" type="text/html" />
  <title type="html"><![CDATA[<%= video.title %>]]></title>
  <summary type="html"><![CDATA[<%= video.description %>]]></summary>
  <category term="<%= video.playlist.title %>" />
  <%- if video.playlist.topic.present? -%>
  <category term="<%= video.playlist.topic.title %>" />
  <%- end -%>
</entry>

app/views/videos/_video.atom.erb
<entry>
  <id><%= video_url(video) %></id>
  <updated><%= video.published_at.iso8601 %></updated>
  <link rel="alternate" href="<%= video_url(video) %>" type="text/html" />
  <title type="html"><![CDATA[<%= video.title %>]]></title>
  <summary type="html"><![CDATA[<%= video.description %>]]></summary>
  <category term="<%= video.playlist.title %>" />
  <%- if video.playlist.topic.present? -%>
  <category term="<%= video.playlist.topic.title %>" />
  <%- end -%>
</entry>

app/views/videos/feed.xml.erb
<?xml version="1.0" encoding="utf-8" ?>
<feed xmlns="http://www.w3.org/2005/Atom" xml:lang="es-ES">
  <title type="text">makigas</title>
  <subtitle type="text">Vídeos recientes publicados en makigas</subtitle>
  <updated><%= @updated_at.iso8601 %></updated>
  <id><%= feed_videos_url %></id>
  <icon><%= URI.join(root_url, 'makigas.png') %></icon>
  <logo><%= URI.join(root_url, 'makigas.png') %></logo>
  <link rel="self" href="<%= feed_videos_url %>" type="application/atom+xml" />
  <link rel="alternate" href="<%= videos_url %>" type="text/html" />
  <author><name>makigas.es</name></author>
  <generator uri="https://github.com/makigas/makigas">makigas.es</generator>
  <%- @videos.each do |video| -%>
    <%= render 'videos/atom', video: video %>
  <%- end -%>
</feed>

app/views/videos/index.atom.erb
<?xml version="1.0" encoding="utf-8" ?>
<feed xmlns="http://www.w3.org/2005/Atom" xml:lang="es-ES">
  <title type="text">makigas</title>
  <subtitle type="text">Vídeos recientes publicados en makigas</subtitle>
  <updated><%= @videos.pluck(:updated_at).max.iso8601 %></updated>
  <id><%= videos_url(format: :atom) %></id>
  <icon><%= URI.join(root_url, 'makigas.png') %></icon>
  <logo><%= URI.join(root_url, 'makigas.png') %></logo>
  <link rel="self" href="<%= videos_url(format: :atom) %>" type="application/atom+xml" />
  <link rel="alternate" href="<%= videos_url %>" type="text/html" />
  <author><name>makigas.es</name></author>
  <generator uri="https://github.com/makigas/makigas">makigas.es</generator>
  <%= render partial: 'video', collection: @videos %>
</feed>

app/views/videos/index.html.haml
- content_for :title, "#{t('.meta.title')} - makigas"
- content_for :description, t('.meta.description')
- content_for :hero, capture { content_tag(:h1) { t('.title') } }
- content_for :canonical, videos_url
- content_for :header do
  %meta{name: :robots, content: :noindex}

.videoexplorer
  = render Six::Base::WrapperComponent.new(classes: 'videoexplorer__wrap') do
    = render Six::Base::ButtonComponent.new(classes: 'videoexplorer__toggle', id: 'sToggleExplorer').with_content('Filtrar por...')
    .videoexplorer__sidebar
      = render Six::Search::BoxComponent.new do |box|
        - box.with_title { 'Filtrar por duración' }
        - box.with_pill(url: derive_search_url(length: nil), icon_right: params[:length] && 'x') { 'Cualquier duración' }
        - video_search_duration_filters.each do |label, filter|
          - box.with_pill(url: derive_search_url(length: filter), active: params[:length] == filter).with_content(label)
      = render Six::Search::BoxComponent.new do |box|
        - box.with_title { 'Filtrar por categoría' }
        - box.with_pill(url: derive_search_url(topic: nil), icon_right: params[:topic] && 'x') { 'Cualquier tema' }
        - Topic.all.find_each do |topic|
          - box.with_pill(url: derive_search_url(topic: [topic.slug]), active: params[:topic].present? && params[:topic].include?(topic.slug)).with_content(topic.title)
      = render Six::Search::BoxComponent.new do |box|
        - box.with_title { 'Filtrar por etiqueta (BETA)' }
        - box.with_pill(url: derive_search_url(tag: nil), icon_right: params[:tag] && 'x') { 'Cualquier vídeo' }
        - Video.tags.sort.each do |tag|
          - box.with_pill(url: derive_search_url(tag: tag), active: params[:tag] == tag).with_content("##{tag}")
    .videoexplorer__list
      = render Six::Search::CurrentFiltersComponent.new(filters: params)
      - if @videos.present?
        = render Six::Search::ResultComponent.with_collection(@videos)
        .paginator= paginate @videos
      - else
        = render Six::Search::EmptyComponent.new(filters: params)

app/views/videos/search_error.html.haml
- content_for :title, "#{t('.meta.title')} - makigas"
- content_for :description, t('.meta.description')
- content_for :hero, capture { content_tag(:h1) { t('.title') } }
- content_for :canonical, videos_url
- content_for :header do
  %meta{name: :robots, content: :noindex}

.videoexplorer
  = render Six::Base::WrapperComponent.new(classes: 'videoexplorer__wrap') do
    = render Six::Base::ButtonComponent.new(classes: 'videoexplorer__toggle', id: 'sToggleExplorer').with_content('Filtrar por...')
    .videoexplorer__sidebar
      = render Six::Search::BoxComponent.new do |box|
        - box.with_title { 'Filtrar por duración' }
        - box.with_pill(url: derive_search_url(length: nil), icon_right: params[:length] && 'x') { 'Cualquier duración' }
        - video_search_duration_filters.each do |label, filter|
          - box.with_pill(url: derive_search_url(length: filter), active: params[:length] == filter).with_content(label)
      = render Six::Search::BoxComponent.new do |box|
        - box.with_title { 'Filtrar por categoría' }
        - box.with_pill(url: derive_search_url(topic: nil), icon_right: params[:topic] && 'x') { 'Cualquier tema' }
        - Topic.all.find_each do |topic|
          - box.with_pill(url: derive_search_url(topic: [topic.slug]), active: params[:topic].present? && params[:topic].include?(topic.slug)).with_content(topic.title)
      = render Six::Search::BoxComponent.new do |box|
        - box.with_title { 'Filtrar por etiqueta (BETA)' }
        - box.with_pill(url: derive_search_url(tag: nil), icon_right: params[:tag] && 'x') { 'Cualquier vídeo' }
        - Video.tags.sort.each do |tag|
          - box.with_pill(url: derive_search_url(tag: tag), active: params[:tag] == tag).with_content("##{tag}")
    .videoexplorer__list
      = render Six::Search::CurrentFiltersComponent.new(filters: params)
      = render Six::Search::SearchErrorComponent.new(filters: params)

app/views/videos/show.html.erb
<% content_for :title, "#{@video.position}. #{@video.title} – #{@video.playlist.title} – makigas" %>
<% content_for :description, @video.description %>
<% content_for(:tags, @video.tags.sort.join(' ')) if @video.tags.present? %>
<% content_for :twitter do %>
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:site" content="@makigas">
  <meta name="twitter:title" content="<%= @video.position %>. <%= @video.title %>">
  <meta name="twitter:description" content="<%= @video.description %>">
  <meta name="twitter:image" content="<%= image_url(@video.playlist.card.url, only_path: false) %>">
<% end %>
<% content_for :facebook do %>
  <meta property="og:url" content="<%= canonical_url %>">
  <meta property="og:title" content="<%= @video.position %>. <%= @video.title %>">
  <meta property="og:type" content="website">
  <meta property="og:description" content="<%= @video.description %>">
  <meta property="og:site_name" content="makigas">
  <meta property="og:image" content="<%= image_url(@video.playlist.card.url, only_path: false) %>">
<% end %>
<% content_for :meta do %>
  <%= tag(:link, rel: :alternate, href: playlist_url(@playlist, format: :atom), title: t('.meta.playlist_feed', playlist: @playlist.title), type: 'application/atom+xml') %>
  <%= tag(:link, rel: :alternate, href: topic_url(@playlist.topic, format: :atom), title: t('.meta.topic_feed', topic: @playlist.topic.title), type: 'application/atom+xml') if @playlist.topic.present? %>
  <% if @video.scheduled? %>
    <meta name="robots" content="noindex">
  <% end %>
<% end %>
<% content_for :jsonld, JSON.pretty_generate(video_object_jsonld(@video)).html_safe %>
<% content_for :body_classes, 'video-player-page' %>
<% if @video.playlist.topic %>
  <% content_for :header do %>
    <style>
      .main-header, .hero-tron { background: <%= @video.playlist.topic.color %>; }
      .main-header .navbar-makigas { background: rgba(0, 0, 0, 0.25); }
    </style>
  <% end %>
<% end %>
<article class="videoinfo">
  <section class="videoinfo__head">
    <div class="videoinfo__player">
      <%= render Six::Base::YoutubeEmbedComponent.new(youtube_id: @video.youtube_id) %>
    </div>
  </section>

  <%= render Six::Base::WrapperComponent.new(tag: :section, classes: 'videoinfo__body', breath: true) do %>
    <div class="videoinfo__text">
      <header>
        <%= render(Six::Base::ButtonGroupComponent.new(style: :flex)) do |g| %>
          <%= g.with_button(href: playlist_video_path(@video.higher_item || @video, playlist_id: @playlist), rel: :prev) { 'Vídeo anterior' } %>
          <%= g.with_button(href: playlist_video_path(@video.lower_item || @video, playlist_id: @playlist), rel: :next) { 'Vídeo siguiente' } %>
        <% end %>
        <p class="videoinfo__pldata">
          <%= link_to @video.playlist.title, playlist_path(@video.playlist), class: 'videoinfo__pllink' %>
        </p>
        <h1 class="videoinfo__title"><%= @video.title %></h1>
        <p class="videoinfo__meta">
          <%= content_tag(:time, l(@video.published_at.to_date, format: :long), datetime: @video.published_at.to_time.iso8601) %> &bull;
          <%= t('.duration', duration: running_time(@video.duration)) %>
          <% if @video.tags.present? %>
            &bull;
            <% @video.tags.each do |tag| %>
              <%= link_to "##{tag}", videos_path(tag:), class: 'videoinfo__tag' %>
            <% end %>
          <% end %>
        </p>
        <p class="videoinfo__description">
          <%= @video.description %>
        </p>
      </header>
      <% if @video.show_note.present? %>
        <div class="videoinfo__shownotes">
          <%= to_markdown(@video.show_note.content).html_safe %>
        </div>
      <% else %>
        <div class="videoinfo__nonotes">
          <p>
          <strong>Este vídeo lamentablemente todavía no tiene notas de episodio.</strong>
          Todavía quedan algunos vídeos en este sitio web que no tienen artículos
          de texto por si te gusta más leer que ver vídeos, y parece que esta
          página es una de ellas.

          <% if @video.transcription.present? %>
          Hay una transcripción del audio disponible
          para ayudarte a llegar a este vídeo que puede que te ayude.
          <% end %>
          </p>
          <p class="videoinfo__nonotes__question">
          <strong>¡Ayúdame a saber qué es prioritario y qué no!</strong>
          ¿Te hubiese ayudado encontrar un artículo de texto en esta página junto al vídeo?
          <button class="btn videoinfo__nonotes__btn" id="notes-survey-yes">Sí</button>
          <button class="btn videoinfo__nonotes__btn" id="notes-survey-no">No</button>
          </p>
        </div>
      <% end %>
      <% if @video.transcription.present? %>
        <details class="videoinfo__transcription">
          <summary>Desplegar transcripción del episodio</summary>
          <%= to_markdown(@video.transcription.content).html_safe %>
        </details>
      <% end %>
      <%= render Six::Lesson::QuestionComponent.new(forum: @video.playlist.display_forum_url, utm: forum_utm_params(@video)) %>
    </div>
    <aside class="videoinfo__links">
      <%= render(Six::Lesson::PartOfPlaylistComponent.new(video: @video)) if @video.playlist.present? %>
    </aside>
  <% end %>
</article>