config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Application error routes
  get '/404', to: 'error#not_found', via: :all
  get '/422', to: 'error#unprocessable_entity', via: :all
  get '/500', to: 'error#internal_server_error', via: :all

  # Dashboard routes
  constraints subdomain: 'dashboard' do
    devise_for :users, controllers: { sessions: 'users/sessions' }
    namespace :dashboard, path: '' do
      root to: 'dashboard#index', as: ''
      resources :topics
      resources :videos, only: %i[index new create]
      resources :playlists do
        get :videos, on: :member
        resources :videos, except: %i[index new create] do
          resources :links
          resource :transcription, only: %i[show create update destroy]
          resource :show_note, only: %i[show create update destroy]
          put :move, on: :member
        end
      end
      resources :users
      resources :opinions
      resource :searches, only: %i[show]

      # Pending actions
      namespace :pending do
        resource :tags, only: %w[show update]
        resource :transcriptions, only: :show
        resource :show_notes, only: :show
      end
    end
  end

  # Main application routes
  root to: 'front#index'

  # Early access.
  get '/early' => redirect('http://early.makigas.es', status: 302)
  get '/early/videos', to: 'videos#early', format: :json

  # Legacy RSS feeds, must come first or there will be conflicts.
  get '/videos/feed' => redirect('/videos.atom')
  get '/temas/:topic/feed' => redirect('/temas/%{topic}.atom')
  get '/series/:playlist/feed' => redirect('/series/%{playlist}.atom')

  resources :topics, path: 'temas', only: %i[index show] do
    get :feed, on: :member, format: :xml
  end

  resources :videos, only: :index

  resources :playlists, path: 'series', only: %i[index show] do
    resources :videos, path: '/', only: :show
  end
  get :terms, path: 'terminos', to: 'pages#terms'
  get :privacy, path: 'privacidad', to: 'pages#privacy'
  get :disclaimer, path: 'responsabilidades', to: 'pages#disclaimer'
  get :cookies, to: 'pages#cookies'
  get :discord, to: 'pages#discord'

  get :dnt, to: 'pages#dnt'

  get '/v/:id', to: 'videos#find_by_id'

  # Legacy routes (redirect only).
  get '/videos/:topic/:playlist/episodio/:video' => redirect('/series/%{playlist}/%{video}')
  get '/videos/:topic/:playlist' => redirect('/series/%{playlist}')
  get '/videos/:playlist' => redirect('/series/%{playlist}')

  # Legacy routes for the old topic explorer
  get '/topics/:topic' => redirect('/temas/%{topic}')
  get '/topics/:topic/feed' => redirect('/temas/%{topic}.atom')
  get '/topics' => redirect('/temas')

  # Legacy routes for the text pages.
  get '/terms' => redirect('/terminos')
  get '/privacy' => redirect('/privacidad')
  get '/disclaimer' => redirect('/responsabilidades')
  get '/about/dnt' => redirect('/dnt')

  if Rails.env.development?
    mount Lookbook::Engine, at: '/lookbook'
    match('/delayed_job' => DelayedJobWeb, :anchor => false, :via => %i[get post])
  end
end

app/models/playlist.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: playlists
#
#  id                     :integer          not null, primary key
#  card_content_type      :string
#  card_file_name         :string
#  card_file_size         :bigint
#  card_updated_at        :datetime
#  description            :text             not null
#  forum_url              :string
#  slug                   :string           not null
#  thumbnail_content_type :string
#  thumbnail_file_name    :string
#  thumbnail_file_size    :bigint
#  thumbnail_updated_at   :datetime
#  title                  :string           not null
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  topic_id               :integer
#  youtube_id             :string           not null
#
# Indexes
#
#  index_playlists_on_slug      (slug) UNIQUE
#  index_playlists_on_topic_id  (topic_id)
#
class Playlist < ApplicationRecord
  extend FriendlyId

  friendly_id :title, use: :slugged

  has_attached_file :thumbnail, styles: {
    thumbnail: '100x100>',
    small: '180x180>',
    default: '360x360>',
    hidef: '720x720>'
  }, default_url: '/makigas.png'

  has_attached_file :card, styles: {
    thumbnail: '320x180>',
    small: '640x360>',
    default: '1280x720>'
  }

  scope :sort_by_latest_video, lambda {
    joins(:videos).group('playlists.id').order(Arel.sql('max(videos.published_at) desc'))
  }

  # At least a video must have been published already.
  scope :with_public_videos, lambda {
    with_public_videos = joins(:videos).where('videos.published_at <= ?', DateTime.current)
    Playlist.where(id: with_public_videos.pluck(:id))
  }

  validates :title, presence: true, length: { maximum: 100 }
  validates :description, presence: true, length: { maximum: 1500 }
  validates :youtube_id, presence: true, length: { maximum: 100 }
  validates :thumbnail, presence: true
  validates :card, presence: true
  validates_attachment :thumbnail, content_type: { content_type: %r{\Aimage/.*\z} }
  validates_attachment :card, content_type: { content_type: %r{\Aimage/.*\z} }

  has_many :videos, -> { order(position: :asc) }, inverse_of: :playlist, dependent: :destroy
  belongs_to :topic, optional: true

  def display_forum_url
    return forum_url if forum_url.present?

    return nil if topic.blank?

    all_topics = topic.ancestors.tap { |arr| arr << topic }
    all_urls = all_topics.map(&:forum_url)
    all_urls.reverse.compact.first
  end

  def total_length
    videos.map(&:duration).reduce(0, :+)
  end

  def to_s
    title
  end

  def content_updated_at
    [updated_at, videos.pluck(:updated_at).max].compact.flatten.max
  end

  # Returns a HATEOAS-friendly representation of the thumbnails.
  def icons
    %i[hidef default thumbnail].map do |style|
      { href: thumbnail.url(style),
        type: thumbnail.content_type,
        sizes: thumbnail.styles[style].geometry.gsub('>', '') }
    end
  end

  # Returns a HATEOAS-friendly representation of the cards
  def cards
    %i[default small thumbnail].map do |style|
      { href: card.url(style),
        type: card.content_type,
        sizes: card.styles[style].geometry.gsub('>', '') }
    end
  end

  # Generate the CreativeWorkSeries schema for this Thing.
  # rubocop:disable Metrics/AbcSize
  def creative_work_series
    { name: title,
      description:,
      abstract: description,
      dateCreated: created_at.iso8601,
      dateModified: content_updated_at.iso8601,
      datePublished: videos.first&.published_at&.iso8601,
      keywords: videos.pluck(:tags).flatten.uniq,
      thumbnailUrl: thumbnail.url(:thumb),
      image: card.url(:default) }
  end
  # rubocop:enable Metrics/AbcSize
end

app/controllers/dashboard/playlists_controller.rb
# frozen_string_literal: true

module Dashboard
  class PlaylistsController < Dashboard::DashboardController
    before_action :playlist_set, only: %i[show edit update destroy videos]

    def index
      @playlists = Playlist.order(updated_at: :desc).page(params[:page])
    end

    def show; end

    def new
      @playlist = Playlist.new
    end

    def edit; end

    def create
      @playlist = Playlist.new(playlist_params)
      if @playlist.save
        redirect_to [:dashboard, @playlist], notice: t('.created')
      else
        render :new
      end
    end

    def update
      if @playlist.update(playlist_params)
        redirect_to [:dashboard, @playlist], notice: t('.updated')
      else
        render :edit
      end
    end

    def destroy
      @playlist.destroy!
      redirect_to %i[dashboard playlists], notice: t('.destroyed')
    end

    def videos
      @videos = @playlist.videos
    end

    private

    def playlist_params
      params.require(:playlist).permit(:title, :description, :youtube_id, :forum_url, :topic_id, :card, :thumbnail)
    end

    def playlist_set
      @playlist = Playlist.friendly.find(params[:id])
    end
  end
end

app/controllers/playlists_controller.rb
# frozen_string_literal: true

class PlaylistsController < ApplicationController
  before_action :playlist_set, only: %i[show]

  def index
    @playlists = Playlist.with_public_videos.sort_by_latest_video.page(params[:page]).per(12)
  end

  def show
    respond_to do |format|
      format.any(:html, :json)
      format.atom do
        @videos = Video.visible.where(playlist_id: @playlist.id).order(published_at: :desc)
      end
    end
  end

  private

  def playlist_set
    @playlist = Playlist.friendly.find(params[:id])
    redirect_to @playlist, status: :moved_permanently if params[:id] != @playlist.slug
  end
end

app/controllers/six/playlists_controller.rb
# frozen_string_literal: true

class Six::PlaylistsController < ApplicationController

  layout 'six'

  before_action :playlist_set, only: %i[show feed]

  def index
    @playlists = Playlist.sort_by_latest_video.page(params[:page]).per(12)
  end

  def show; end

  def feed
    @videos = @playlist.videos.includes(:playlist, playlist: [:topic]).visible.reverse
    @updated_at = Video.order(updated_at: :desc).limit(1).pick(:updated_at)
    render format: :xml, template: 'playlists/feed.xml.erb', layout: false
  end

  private

  def playlist_set
    @playlist = Playlist.friendly.find(params[:id])
    redirect_to @playlist, status: :moved_permanently if params[:id] != @playlist.slug
  end
end

app/helpers/playlists_helper.rb
# frozen_string_literal: true

module PlaylistsHelper
  # rubocop:disable Metrics/MethodLength
  def playlist_jsonld(playlist)
    playlist.creative_work_series.deep_merge(
      '@context': 'https://schema.org/',
      '@type': 'CreativeWorkSeries',
      publisher: {
        '@type': 'Organization',
        name: 'makigas',
        url: 'https://www.makigas.es'
      },
      url: playlist_path(playlist),
      sameAs: "https://www.youtube.com/playlist?list=#{playlist.youtube_id}",
      author: {
        '@type': 'Person',
        name: 'Dani Rodríguez'
      }
    )
  end
  # rubocop:enable Metrics/MethodLength
end

app/views/playlists/contents.html.erb
<h1><%= link_to @playlist.title, playlist_path(@playlist) %>
<h2><%= t('.title') %></h2>

<table class="table table-default">
  <thead>
    <tr>
      <th><%= t('.position') %></th>
      <th><%= t('.episode') %></th>
      <th colspan="2"><%= t('.operations') %></th>
    </tr>
  </thead>
  <tbody>
    <% @playlist.videos.each do |video| %>
    <tr>
      <td><%= video.position %></td>
      <td class="col-expand"><%= link_to video.title, playlist_video_path(video, playlist_id: @playlist) %></td>
      <td class="col-mini">
        <%= button_to sort_playlist_path(@playlist), class: 'btn btn-default btn-xs', method: :put do %>
          <%= hidden_field_tag :video, video.id %>
          <%= hidden_field_tag :operation, :up %>
          <%= t('.up') %>
        <% end unless video.first? %>
      </td>
      <td class="col-mini">
        <%= button_to sort_playlist_path(@playlist), class: 'btn btn-default btn-xs', method: :put do %>
          <%= hidden_field_tag :video, video.id %>
          <%= hidden_field_tag :operation, :down %>
          <%= t('.down') %>
        <% end unless video.last? %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/playlists/index.html.erb
<% content_for :title, "#{t('.meta.title')} – makigas" %>
<% content_for :description, t('.meta.description') %>
<% content_for :hero do %>
  <h1><%= t('.title') %></h1>
<% end %>
<%= render Six::Explorer::PlaylistListComponent.new(playlists: @playlists) %>
<div class="paginator">
  <%= paginate @playlists %>
</div>

app/views/playlists/show.atom.erb
<?xml version="1.0" encoding="utf-8" ?>
<feed xmlns="http://www.w3.org/2005/Atom" xml:lang="es-ES">
  <title type="text"><%= @playlist.title %></title>
  <subtitle type="text">Una lista de reproducción de makigas</subtitle>
  <updated><%= @videos.pluck(:updated_at).max.iso8601 %></updated>
  <id><%= playlist_url(@playlist, format: :atom) %></id>
  <icon><%= @playlist.thumbnail.url %></icon>
  <logo><%= @playlist.thumbnail.url %></logo>
  <link rel="self" href="<%= playlist_url(@playlist, format: :atom) %>" type="application/atom+xml" />
  <link rel="alternate" href="<%= playlist_url(@playlist) %>" type="text/html" />
  <author><name>makigas.es</name></author>
  <generator uri="https://github.com/makigas/makigas">makigas.es</generator>
  <%= render partial: 'videos/video', collection: @videos %>
</feed>

app/views/playlists/show.html.erb
<% content_for :title, "#{@playlist.title} – makigas" %>
<% content_for :description, @playlist.description %>
<% content_for :twitter do %>
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:site" content="@makigas">
  <meta name="twitter:title" content="<%= @playlist.title %>">
  <meta name="twitter:description" content="<%= @playlist.description %>">
  <meta name="twitter:image" content="<%= image_url(@playlist.card.url, only_path: false) %>">
<% end %>
<% content_for :facebook do %>
  <meta property="og:url" content="<%= canonical_url %>">
  <meta property="og:title" content="<%= @playlist.title %>">
  <meta property="og:type" content="website">
  <meta property="og:description" content="<%= @playlist.description %>">
  <meta property="og:site_name" content="makigas">
  <meta property="og:image" content="<%= image_url(@playlist.card.url, only_path: false) %>">
<% end %>
<% content_for :meta do %>
  <%= tag(:link, rel: :alternate, href: playlist_url(@playlist, format: :atom), title: t('.meta.playlist_feed', playlist: @playlist.title), type: 'application/atom+xml') %>
  <%= tag(:link, rel: :alternate, href: topic_url(@playlist.topic, format: :atom), title: t('.meta.topic_feed', topic: @playlist.topic.title), type: 'application/atom+xml') if @playlist.topic.present? %>
<% end %>
<% content_for :jsonld, JSON.pretty_generate(playlist_jsonld(@playlist)).html_safe %>
<% if @playlist.topic %>
  <% content_for :header do %>
    <style>
      :root {
        --navbar-background: <%= @playlist.topic.color.paint.darken(20) %>;
        --playlist-background: <%= @playlist.topic.color.paint.darken(20) %>;
        --video-card-hover-background: <%= @playlist.topic.color.paint.desaturate(35).lighten(35) %>;
      }
    </style>
  <% end %>
<% end %>
<% content_for :jumbo do %>
  <%= render Six::Layout::PlaylistHeaderComponent.new(playlist: @playlist) %>
<% end %>
<%= render Six::Base::WrapperComponent.new(breath: true, classes: 'playlistsdata') do %>
  <% @playlist.videos.visible.each do |v| %>
    <%= render Six::Explorer::PlaylistVideoCardComponent.new(video: v) %>
  <% end %>
<% end %>